// Recognizer audio - tensorFlow.speech -
export const SET_RECOGNIZER_AUDIO_SAGA = "SET_RECOGNIZER_AUDIO_SAGA"
export const SET_RECOGNIZER_AUDIO_LOADED = "SET_RECOGNIZER_AUDIO_LOADED"
export const SET_RECOGNIZER_AUDIO_ERROR = "SET_RECOGNIZER_AUDIO_ERROR"