// Recognizer audio - tensorFlow.speech -
export const SET_RECOGNIZER_AUDIO_SAGA = "SET_RECOGNIZER_AUDIO_SAGA"
export const SET_RECOGNIZER_AUDIO_LOADED = "SET_RECOGNIZER_AUDIO_LOADED"
export const SET_RECOGNIZER_AUDIO_ERROR = "SET_RECOGNIZER_AUDIO_ERROR"

// Start/Stop recognizer speech.
export const START_RECOGNIZER_SPEECH_SAGA = "START_RECOGNIZER_SPEECH_SAGA"
export const RECOGNIZER_SPEECH = "RECOGNIZER_SPEECH"
export const STOP_RECOGNIZER_SPEECH = "STOP_RECOGNIZER_SPEECH"